"""Reusable runtime primitives for Career Job Agent deployments."""

from .changes import (
    DEFAULT_EVALUATION_FIELDS,
    DEFAULT_MATERIAL_FIELDS,
    detect_evaluation_changes,
    detect_material_changes,
    get_field,
    normalize_comparable,
)
from .config import (
    ConfigError,
    ConfigSource,
    deep_merge,
    load_config_directory,
    load_config_file,
    load_config_overlay,
    load_config_source,
    load_overlay_chain,
    parse_simple_yaml,
    select_private_config_source,
)
from .connectors import (
    AlertMessage,
    ConnectorError,
    DeliveryResult,
    DiscoveryBatch,
    DiscoveryConnector,
    DiscoveryRequest,
    EmailAlertConnector,
    ReportConnector,
    VerificationConnector,
)
from .identity import (
    are_duplicate_jobs,
    canonical_job_identity,
    coerce_job,
    dedupe_jobs,
    deduplicate_jobs,
    job_identity_keys,
    merge_job_records,
    normalize_text,
)
from .models import (
    ApplicationRecord,
    ChangeRecord,
    CoverageRecord,
    InstitutionCoverageRecord,
    JobRecord,
    JsonModel,
    JsonValue,
    RunRecord,
    SourceAuthority,
    SourceClass,
    SourceCoverageRecord,
    SourceRecord,
    UpsertResult,
    VerificationResult,
    VerificationStatus,
    json_safe,
    utc_now,
)
from .privacy import (
    PrivacyFinding,
    PrivacyGuard,
    PrivacyViolation,
    PublicReleaseGuard,
)
from .sources import (
    apply_verification,
    choose_authoritative_source,
    source_authority,
    verification_can_close,
    verification_is_authoritative,
)
from .state import (
    STATE_SCHEMA_VERSION,
    TABLES,
    InMemoryStateStore,
    JsonFileStateStore,
    StateStore,
    StateStoreError,
)
from .urls import canonicalize_url, normalize_url, urls_equal
from .validation import (
    SchemaValidationError,
    ValidationIssue,
    require_json_mapping,
    validate_mapping,
)


# Compatibility aliases for deployments that used generic names in prototypes.
Job = JobRecord
Source = SourceRecord
JSONFileStateStore = JsonFileStateStore
InMemoryStore = InMemoryStateStore


__all__ = [
    "AlertMessage",
    "ApplicationRecord",
    "ChangeRecord",
    "ConfigError",
    "ConfigSource",
    "ConnectorError",
    "CoverageRecord",
    "DEFAULT_EVALUATION_FIELDS",
    "DEFAULT_MATERIAL_FIELDS",
    "DeliveryResult",
    "DiscoveryBatch",
    "DiscoveryConnector",
    "DiscoveryRequest",
    "EmailAlertConnector",
    "InMemoryStateStore",
    "InMemoryStore",
    "InstitutionCoverageRecord",
    "Job",
    "JobRecord",
    "JSONFileStateStore",
    "JsonFileStateStore",
    "JsonModel",
    "JsonValue",
    "PrivacyFinding",
    "PrivacyGuard",
    "PrivacyViolation",
    "PublicReleaseGuard",
    "ReportConnector",
    "RunRecord",
    "STATE_SCHEMA_VERSION",
    "SchemaValidationError",
    "Source",
    "SourceAuthority",
    "SourceClass",
    "SourceCoverageRecord",
    "SourceRecord",
    "StateStore",
    "StateStoreError",
    "TABLES",
    "UpsertResult",
    "ValidationIssue",
    "VerificationConnector",
    "VerificationResult",
    "VerificationStatus",
    "apply_verification",
    "are_duplicate_jobs",
    "canonical_job_identity",
    "canonicalize_url",
    "choose_authoritative_source",
    "coerce_job",
    "dedupe_jobs",
    "deduplicate_jobs",
    "deep_merge",
    "detect_evaluation_changes",
    "detect_material_changes",
    "get_field",
    "job_identity_keys",
    "json_safe",
    "load_config_directory",
    "load_config_file",
    "load_config_overlay",
    "load_config_source",
    "load_overlay_chain",
    "merge_job_records",
    "normalize_comparable",
    "normalize_text",
    "normalize_url",
    "parse_simple_yaml",
    "require_json_mapping",
    "select_private_config_source",
    "source_authority",
    "urls_equal",
    "utc_now",
    "validate_mapping",
    "verification_can_close",
    "verification_is_authoritative",
]
